### ISSUE TITLE
Link to the image broken

### ISSUE THREAD

**Issue by rgruosso** [spectroman/mmm-moon-phases#1]
Hello spectroman

I have just loaded your module on my mirrors. Unfortunately, the image is not displayed in the mirror. Under the link is no image available.

**Comment by spectroman** [comment]
Well it seems that you had bad luck to test when they were offline or something... if you put the image url on your browser: http://api.usno.navy.mil/imagery/moon.png and that works, may mean that your magic mirror is not reaching the web address... check these options out!
