### ISSUE TITLE
New Module: EarthAndMoon

### ISSUE THREAD

**Issue by joelman** [spectroman/mmm-moon-phases#5]
Great work on your module; I love it. But I also love the [Earth Module](https://github.com/mykle1/MMM-EARTH). So I came up with an idea of how to combine them. [Earth and Moon](https://github.com/joelman/MMM-EarthAndMoon) toggles between earth and moon at sunrise and sunset. Please give it a try and let me know what you think!

There are sample config values in the code.

Joel

**Comment by spectroman** [comment]
not an issue
