### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by shane190588** [spectroman/mmm-moon-phases#8]
The url this module points towards seems to no longer be available (deemed unsafe) so now only displays an empty box. Shame as this was a beautiful module to have displayed along with time/date and weather. Have attempted to run on various other instances or MM on different devices to only end with the same result. Would love to see this working again if there is potentially another source url or a work around for not being deemed secure?

**Comment by spectroman** [comment]
fixed. fording https and disabling certificate checks
